### ISSUE TITLE
Index button in issues is white

### ISSUE THREAD

**Issue by W2Wizard** [FreekBes/improved_intra#12]
Index button is white, also overwrite these classes:

<img width="1322" alt="Screen Shot 2022-03-09 at 8 23 07 PM" src="https://user-images.githubusercontent.com/63303990/157516234-0c8f5c30-ecc5-4af8-bab0-53941fb2a5ca.png">

```css
.topic-item .topic-content .topic-metadata {
    color: rgba(103,103,109,0.5);
}
```
